spring:
  application:
    name: yun-ai-agent
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/yun_ai_agent
    username: postgres
    password: 123456
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
server:
  port: 8492
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.thefang.yunaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn